### ISSUE TITLE
Error: bash: ./PVRTexToolCLI: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by fourk0** [linkabox/KTXConverter#1]
When I try to run the program on Windows it does not work and retruns this error:
`bash: ./PVRTexToolCLI: cannot execute binary file: Exec format error` for every file in the folder

**Comment by pitust** [comment]
did you try using linux?

**Comment by pitust** [comment]
No sorry, did you try using mac os?

**Comment by sergiyz57918** [comment]
You need to install PowerVRTools https://www.imaginationtech.com/developers/powervr-sdk-tools/installers/ use Linux download.
Install it on your Linux machine by running ./PVRTexToolSetup-2020_R2.run-x64, note where it installed in the home directory.  cd there and copy PVRTexToolCLI to where your convertktx.sh file is. You should be able to run it. One more thing, make sure to create output directory by running mkdir output
